default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>


development:
  <<: *default
  database: doctors_api_app_development
test:
  <<: *default
  database: doctors_api_app_test
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    schema_search_path: doctors,public
    pool: 5
    timeout: 5000
  cache:
    <<: *primary_production
    database: doctors_api_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: doctors_api_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: doctors_api_app_production_cable
    migrations_paths: db/cable_migrate