default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>


development:
  <<: *default
  database: doctors_api_app_development
test:
  <<: *default
  database: doctors_api_app_test
production:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>